const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Kuber Mirajakar";
const email = 'Email';
const emailHint = "amin@admin.com";
const password = 'Password';
const passwordHint = '***********';
const reTypePassword = "ReType Password";
const name = "Name";
const nameHint = "Kuber m";
const forgetPassword = "Forgot Password";
const signUp = "Sign up";
const signIn = "Sign in";
const createNewAccount = "or, create a new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termsAndCondition = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account? ";

const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
